### ISSUE TITLE
Scraper Frequency

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#10]
Hello. is there a way to get torrents any quicker? its been 2 days now and ive only got to 20k. where as my friend installed at the same time and has 268k lol.

Thanks in advanced

**Comment by Raxvis** [comment]
Are you hosting this locally  (at home / at work) or on a server somewhere?

**Comment by ghost** [comment]
It's on a bare metal server hosted at scaleway which is basically online.net

**Comment by Raxvis** [comment]
Is it on the same as your friends?

You might want to increase the connection limit (https://github.com/AlphaReign/scraper/blob/master/config.js).  It could also be that your host doesn't allow port forwarding on port 6881 or that your node isn't very deep in the DHT network.

Also, starting / stopping it will kill any peer network it has.

If all that fails, you can trying on digital ocean for a few hours for not a lot of cost and see if that changes things

**Comment by ghost** [comment]
No my friends is on a different host/country. 
What would you recommend changing the value to?

I have tried another DHT scraper before this one and that scrapes like crazy so I wouldn't thought it would be a port issue ?

Thanks for your reply

**Comment by Raxvis** [comment]
What other DHT scraper did you use?

I would assume it's  because you aren't deep in the DHT Network and only have a few nodes querying through your node.  Hosting it in a more central location (US West or US East) will definitely increase the speed.  Hosting multiple nodes in different continents will give you the most possible along with picking up things that aren't available elsewhere

**Comment by ghost** [comment]
It was https://github.com/fanpei91/p2pspider/blob/master/README.md

It's in go language and I modified it to write directly to mysql but mysql sucks for speed compared to yours .

Currently The server is in France . And my friends in Romania . I'll try some different hosts

**Comment by Raxvis** [comment]
Okay.

You could always rewrite the p2pspider it to push to elasticsearch

**Comment by ghost** [comment]
unfortuantly im not to great in Golang to do that. and also the seeds/peer update i have no idea how to do that in Golang. Thats why i like your project :) ill try moving servers like you said see if that helps :)
thanks mate

**Comment by ash121121** [comment]
Seems like changing hosts works. Before closing could i ask a question please. whats the specifications required/optimized to run a large instance of AR like 10 million torrents or more?

kind regards

**Comment by Raxvis** [comment]
To run 10 million torrents, you will probably need 16-32 Gigs of ram for elastic search if you want to sub second response times.  You could do it with less, I just don't know the latency that would be caused by that.

**Comment by ghost** [comment]
thanks for that information i appreciate it. one last question withought becoming annoying :D . i have a text file with millions of hash entrys.. would it be possible to use the scraper to import the hashes from this file and grab the torrent information?

kind regards

**Comment by Raxvis** [comment]
Yes, it is possible.  A script would have to be written to read the files and then parse the torrent files and then scrape the information from the torrent files and the dht network
