### ISSUE TITLE
Timed out

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#11]
Hey its me again. i was searching through the logs and im seeing this quite alot. ive tried a range of different trackers and seeing the same. Hope  you can help. thanks

 index > Error: tracker request timed out (undefined) (udp://tracker.coppersurfer.tk:6969/announce)               x
x                                                xx index >     at Timeout.<anonymous> (/root/scraper/node_modules/bittorrent-tracker/lib/client/udp-tracker.js:92:  x
x                                                xx 18)                                                                                                              x
x                                                xx index >     at ontimeout (timers.js:386:11)                                                                      x
x                                                xx index >     at Timer.unrefdHandle (timers.js:492:5)

**Comment by Raxvis** [comment]
it's most likely because you are processing more torrents than the tracker can handle

**Comment by ghost** [comment]
I see . So I guess I need to decrease max connections ?
Another question before I close . Just trying to wrap my head around the whole project :) how does the seeders/peers get updated once they are in the database ? Like once a torrent enters the database with seeders information , does this torrent ever get its seeders updated again ?

Kind regards

**Comment by Raxvis** [comment]
scraper.js constantly runs to grab the oldest updated torrents and get the seeders and leechers.  This ensures everything keeps up to date

**Comment by ghost** [comment]
Thanks for that information :)

**Comment by ghost** [comment]
Im getting some torrents added that dont contain any seeder information. for example it doesnt even show 0/0

could this be because of the tracker timing out?

thanks in advanced

**Comment by Raxvis** [comment]
That is probably correct. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
Seems to be every single torrent from now is entering with 0/0 ive checked manually against the same tracker and they indeed do have seeds/leech values. You have any suggestions to why this might be happening?

**Comment by ghost** [comment]
seems i cant access any scrapers and im pulling my hair out lol..
xx index >     at Timer.unrefdHandle (timers.js:492:5)                                                              x
x                                                xx index > Error: tracker request timed out (undefined) (udp://tracker.coppersurfer.tk:6969/announce)               x
x                                                xx index >     at Timeout.<anonymous> (/root/scraper/node_modules/bittorrent-tracker/lib/client/udp-tracker.js:92:  x
x                                                xx 18)                                                                                                              x
x                                                xx index >     at ontimeout (timers.js:386:11)                                                                      x
x                                                xx index >     at Timer.unrefdHandle (timers.js:492:5)

**Comment by Raxvis** [comment]
Try to manually scrape with the code and see if that works. It might be that your IP is blocked because it’s black listed 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by Raxvis** [comment]
Scrape from the server is what I mean 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by ghost** [comment]
i tried a fresh server with a different ip and seems the same. i can scrape the tracker with with  php so im guessing its not a ip block?

**Comment by ghost** [comment]
Just to be sure im not doing anything wrong here this is how i installed.
Centos 7.3
Yum update
Download or clone the repository
Install node / npm
Install elasticsearch
Install pm2 globally (npm install -g pm2)
Update package.json -  "elasticsearch": "^11.0.1" TO  "elasticsearch": "^14.0.0",
cd scraper/
npm install
Update config.json

Thanks for you help

**Comment by ghost** [comment]
Ok so my friend used his server to send data to my elastic db and although he's not getting the tracker timeout mostly all new torrents being added have 0/0 seeders/leechers . I checked the ones that have 0/0 against cooperurf and they appear to have seeders information .

**Comment by ghost** [comment]
^^ btw sorry for the million messages I've posted ^^

**Comment by Raxvis** [comment]
You could have a bad mapping in elasticsearch.

Did you map elasticsearch with this file: https://github.com/AlphaReign/scraper/blob/master/mapping.json before you started?

**Comment by ghost** [comment]
I'm just getting grips with elastic search so I'll need some advice on how to do that. Don't worry I'm not respecting you too it's not your issue, but if you can :)
Also I restored from a previous dump of elastic search . Could of this messed things up ?

**Comment by ghost** [comment]
Sorry typos dam auto correct

**Comment by Raxvis** [comment]
Potentially.  Here is a link to put a mapping.

https://www.elastic.co/guide/en/elasticsearch/reference/current/indices-put-mapping.html

You will need to delete the current search index though

**Comment by ghost** [comment]
I see I'll give it a go thanks . At the moment I have half a million torrents. I'm guessing I'll have to start fresh ?

**Comment by Raxvis** [comment]
Yes

**Comment by ghost** [comment]
Thanks mate will give it a go :)

**Comment by ghost** [comment]
So just for reference this step everybody should be doing ? Or just me

**Comment by Raxvis** [comment]
It should be done by everyone

**Comment by ghost** [comment]
Thanks buddy . If so could you put this in your readme? And possible how to do it correctly ? I'll leave you alone now hehe 
 Kind regards

**Comment by ghost** [comment]
I did a fresh server and did that extra step but still out of maybe 100 torrents entering the database only a few have seeders/leechers .

Thanks in advanced

**Comment by ghost** [comment]
I'm about to give up lol it's a shame because this script is perfect for me :(
I've tried multiple server hosts and same issue with if not adding the seeders and leechers .

**Comment by Raxvis** [comment]
Okay, good luck

**Comment by ghost** [comment]
Is there any more help you could chuck my way please ? Could you maybe test for yourself and see if you also get this issue ? Im sorry I can't contribute but I can send some money your way if you like . I'm so excited to have a working copy of your project

**Comment by Raxvis** [comment]
Sounds good.  Shoot me an email at prefinem@gmail.com so I can look into the specifics of your setup

**Comment by ghost** [comment]
Thanks mate I sent you a email

**Comment by ghost** [comment]
did you get it?

**Comment by Raxvis** [comment]
Yes. I will reply tomorrow. Sorry but it’s been a long week

**Comment by ghost** [comment]
np mate. same here. i thought you didnt get notifcations once a issue is closed.

**Comment by ghost** [comment]
If you have time im free tonight?
