### ISSUE TITLE
No torrents need to be scraped 

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#12]
Hey its me again mate. i know your probally super busy but i tried again. This time i managed to fix the issue with the tracker timing out. it appears that running the scraper - elastic search and the front end breaks the tracker. Maybe some firewall or something gets installed along the way.. 
Anyway..
im now running the scraper and elastic on its own VPS and the front end on its own VPS..

But now im at that issue were only some torrents are entering the database with seeders/leechers information.
It seems on first boot running "pm2 start ./dist/index.js
"
it shows its updating peers etc. but then after this each torrent im getting "No torrents need to be scraped "

Any help on this would be much appreciated. And do you have some way i can donate to this project to help.

kind regards

**Comment by Raxvis** [comment]
"No torrents need to be scraped" mean that all torrents have been scraped
with a 24 hour time period.  That means you are good to go

**Comment by ghost** [comment]
Great looks like I'm getting somewhere. Right now I have scraper on a digital ocean server and elastic . But I plan to move elastic to a separate server. Is there anything I need to do apart from install elastic at the new host and edit config.js in the scraper to point to the new elastic ?. Do I need to install the mapping from mapping.json

Kind regards

**Comment by Raxvis** [comment]
If you backup elastic, and restore it, you won't need to do that mapping at
all.

Change the config.js and then, in the www-php version, you will need to
change the config for that as well.

**Comment by ghost** [comment]
That's true I'll give it a go thanks.  Send me your PayPal for donation

**Comment by Raxvis** [comment]
Here is a link:
https://www.paypal.com/cgi-bin/webscr?cmd=_s-xclick&hosted_button_id=WZ7244UCPG6GN

**Comment by ghost** [comment]
ive sent a little donation for now mate :)
a few questions.
Do you have any dumps from AR? i seen a RDP dump in one of the issues. can this be imported into elastic?
is there a way to manually update all seeders info?

kind regards

**Comment by Raxvis** [comment]
The Redis dump (RDP) is just a list of torrent hashes with information.  To
export, you have to spin up a redis serve, and then import the dump, and
then select out records and insert them into elasticsearch

**Comment by Raxvis** [comment]
Manually updating seeders would require you to update the torrent and set
the last updated time to something like 0, where the automated process will
pick it up.

**Comment by Raxvis** [comment]
Or, you can update the peerAge in the config to 1 and it will update any
torrents not updated in the last minute

**Comment by ghost** [comment]
Great thanks for the info. if your interested in a little bit of freelance work let me know because i have a few mods to your script id like.

once again thanks for the support and such a great script

**Comment by Raxvis** [comment]
Maybe but probably not for the next couple of days since I am in the middle
of another project. What scripts are you looking for?

**Comment by ghost** [comment]
no problem mate. well for a start id like to import skytorrents 5 million hashes and pass them along DHT to get the information and put in elastic... is that possible? they are in a txt file

**Comment by Raxvis** [comment]
That is possible for sure.

**Comment by ghost** [comment]
nice. if you could send me a quote via email when your free and we can go from there?

**Comment by Raxvis** [comment]
Sounds good

**Comment by ghost** [comment]
Closing issue... Thanks mate looking forward to an email.
