### ISSUE TITLE
File size bug

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#13]
Hey. It seems some torrents are entering into elastic with 0B of size. but upon opening the magnet into Utorrent, it indeed has file size.

Can you shed any light onto this?

kind regards

**Comment by Raxvis** [comment]
Some torrents can't get size from the DHT network and must start
downloading the file to get the size.

**Comment by ghost** [comment]
What do you propose for as work around? Maybe skill torrents if 0b in size ?

**Comment by ghost** [comment]
Skip

**Comment by Raxvis** [comment]
You can.  I usually don't show the size if size is 0

**Comment by ghost** [comment]
i managed to get this bug fixed if you liked to push to update yours?

**Comment by Raxvis** [comment]
That would be awesome!

**Comment by ash121121** [comment]
Here you go. enjoy

[indexer.zip](https://github.com/AlphaReign/scraper/files/1804823/indexer.zip)

**Comment by ghost** [comment]
[src_dist_index_js.zip](https://github.com/AlphaReign/scraper/files/1804834/src_dist_index_js.zip)
Here you go.

**Comment by Raxvis** [comment]
If you are familiar with git, you can fork this repo and create a pull
request with your changes.

**Comment by ghost** [comment]
Sorry not used git that much :D

**Comment by Raxvis** [comment]
No problem
