### ISSUE TITLE
Miltiple scrapers

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#14]
hi. is it possible to have multiple instances running of the scraper in different regions, pointing to the same elastic DB. will there be issues with duplicates torrents.

kind regards

**Comment by Raxvis** [comment]
Nope, that works just fine.  Elasticsearch handles the duplicates

**Comment by ghost** [comment]
Thanks mate. One last question if possible.  I'm seeing some bad stuff end up on the site from DHT like underage porn etc.. What's your thoughts on a way to stop this? I was thinking of using your categorized.js and use keywords to make torrent inactive.

Kind regards

**Comment by Raxvis** [comment]
categorized.js would be the perfect place for it.

**Comment by ghost** [comment]
Thanks for that info mate. ive added some stuff in. Now just to figure out how to delete all that bad stuff thats all ready entered the DB.. there a way to run catagorize.js for the whole db or is it only doing it as new torrents enter?

kind regards

**Comment by Raxvis** [comment]
You could probably create an elasticsearch query that deletes the records
that match a certain query.  The categorize.js only works on new torrents
coming in.  It may work on ones that are re-indexed as well

**Comment by ghost** [comment]
Thanks matte appreciate your input.  The shit that comes from DHT is crazy .. like if you don't filter stuff as a public site your screwed . You could get done for facilitating 
This bad stuff ( won't name it but u No) anyways https://skytorrents.lol is powered by AR with a lot of mods.  Thanks for input

**Comment by ghost** [comment]
Maybe I'm missing something but I added a keyword into the inactive array of categorized.js but torrents with the keyword still in the DB .

**Comment by ghost** [comment]
Maybe I need to study categorized.js maybe it's not matching the keywords properly.  I suck at js but what I'm trying to achieve  is like in php  with stripos

**Comment by Raxvis** [comment]
indexOf is the function you are like looking for.

**Comment by ghost** [comment]
Thanks looks like its working :) i used tolowercase.indexOf ... thanks again mate

**Comment by Raxvis** [comment]
Awesome!
