### ISSUE TITLE
scraper.js and categorize.js error

### ISSUE THREAD

**Issue by onigumo1990** [AlphaReign/scraper#2]
Hello, I'm getting the following error that's being repeated multiple times in both scrape.js and categorize.js

`Trace: [index_not_found_exception] no such index, with { resource.type=index_or_alias resource.id=torrents index_uuid=_na_ index=torrents }
    at /var/www/html/alphareign/scraper/scrape.js:34:17
    at tryCallOne (/var/www/html/alphareign/scraper/node_modules/promise/lib/core.js:37:12)
    at /var/www/html/alphareign/scraper/node_modules/promise/lib/core.js:123:15
    at flush (/var/www/html/alphareign/scraper/node_modules/asap/raw.js:50:29)
    at _combinedTickCallback (internal/process/next_tick.js:67:7)
    at process._tickDomainCallback [as _tickCallback] (internal/process/next_tick.js:122:9)`

I have ran npm install and installed ElasticSearch, here is the status of ElasticSearch:
```
$ service elasticsearch status
● elasticsearch.service - Elasticsearch
   Loaded: loaded (/usr/lib/systemd/system/elasticsearch.service; enabled; vendor preset: enabled)
   Active: active (running) since Sat 2017-03-04 09:38:15 CST; 7h ago
     Docs: http://www.elastic.co
  Process: 18645 ExecStartPre=/usr/share/elasticsearch/bin/elasticsearch-systemd-pre-exec (code=exited, status=0/SUCCESS)
 Main PID: 18649 (java)
    Tasks: 49
   Memory: 112.4M
      CPU: 1min 32.176s
   CGroup: /system.slice/elasticsearch.service
           └─18649 /usr/bin/java -Xms2g -Xmx2g -XX:+UseConcMarkSweepGC -XX:CMSInitiatingOccupancyFraction=75 -XX:+UseCMSInitiatingOccupancyOnly -XX:+DisableExplicitGC -XX:+AlwaysPreTouch -server -Djava.awt.headless=true -Dfile.encoding=UTF-8 -Djna.nosys=true -Dio.netty.noUnsafe=true -Dio.netty.noKeySetOptimization=true -Dlog4j.shutdownHookEnabled=false -Dlog4j2.disable.jmx=true -Dlog4j.skipJansi=true -XX:+HeapDumpOnOutOfMemoryError -Des.path.home=/usr/share/elasticsearch -cp /usr/share/elasticsearch/lib/elasticsearch-5.0.0.jar:/usr/share/elasticsearch/lib/* org.elasticsearch.bootstrap.Elasticsearch -p /var/run/elasticsearch/elasticsearch.pid --quiet -Edefault.path.logs=/var/log/elasticsearch -Edefault.path.data=/var/lib/elasticsearch -Edefault.path.conf=/etc/elasticsearch

Mar 04 09:38:15 ubuntu-services systemd[1]: Starting Elasticsearch...
Mar 04 09:38:15 ubuntu-services systemd[1]: Started Elasticsearch.
Mar 04 09:38:21 ubuntu-services elasticsearch[18649]: [2017-03-04T09:38:21,430][WARN ][o.e.c.l.LogConfigurator  ] ignoring unsupported logging configuration file [/etc/elasticsearch/logging.yml], logging is configured via [/etc/elasticsearch/log4j2.properties]
```

**Comment by Raxvis** [comment]
Before you run scrape or categorize, you will need add.js to run and add torrents.  It will create the index in elasticsearch

**Comment by onigumo1990** [comment]
How long must add.js run because it's been running most of the day?

**Comment by Raxvis** [comment]
run the command "pm2 logs add"

If you see it adding torrents, you should be good to go.  If you don't see any torrents being added (and have been connected for a half a day) you might be running into an issue where the DHT port isn't exposed and thus not getting requests.

Are you using a hosting provider or at home?

**Comment by onigumo1990** [comment]
Whoops, my mistake. I had it running most of the day and I tried to start fresh when I thought it wasn't working for me.

I currently have 1 added line. I'm doing this from home on a Linux VM.

**Comment by Raxvis** [comment]
Did you just restart it or one added line for running all of today?

**Comment by onigumo1990** [comment]
add.js has been running for 23m according to "pm2 list" and I have 1 added so far. In my previous attempt before I wiped it, I think I had around 8 or so and that was probably a couple hours at least.

**Comment by Raxvis** [comment]
Gotcha.  I would recommend moving the node / scraper stuff to a small digital ocean server  (5 bucks a month) and point that to your home ElasticSearch.  You can use ngrok to expose your home ElasticSearch.

The reason being is that your home network probably won't get a lot of DHT traffic, but one on Digital Ocean  (or another hosting provider) will

**Comment by onigumo1990** [comment]
I definitely don't want to do that, at least until I've gotten everything figured out. Thanks for your help! =)

**Comment by Raxvis** [comment]
NP.  If you are getting one or two, you might be able to keep it running for a few days letting it pick up more DHT nodes

**Comment by onigumo1990** [comment]
It looks like scraper.js is no longer erroring, I'm not sure exactly what is going on, I didn't really do much, but since it's working this issue has been resolved.

**Comment by Raxvis** [comment]
Just a final resolve on this, so if others run into this issue.

add.js only adds in bulk (every 1000).  This can be modified if needed.  If you haven't added any torrents to ElasticSearch, both scraper.js and categorizer.js will fail
