### ISSUE TITLE
DHT Crawler does not seem to work

### ISSUE THREAD

**Issue by simionrobert** [AlphaReign/scraper#21]
Hi.

I ran index.js and no infohashes were to be found, no matter how much time I let him run.
I opened a network analyser and I saw several packets are sent continously over the network. I also disabled the firewall.

Is it still working now?

Thank you.

**Comment by Raxvis** [comment]
You will have to host this on a host that can be queried by other DHT nodes, so if you are at home behind a router or don't have a static IP, then it will not work.

**Comment by simionrobert** [comment]
Hi. I am behind the phone hotspot. However, I wrote myself a piece of code that works on this case, that does the same thing, with modifications on messages replies and requests. It works on this case.

What do you think?

**Comment by Raxvis** [comment]
This won't work behind a phone hotspot.  The idea of the code is to act as a good DHT node and pass requests back and forth.  All it does after that is record which requests are being sent back and forth.

How are you getting requests forwarded to your node?

**Comment by simionrobert** [comment]
Periodically, I send findNodeReq to bootstrap nodes with a static id to populate the routing tables with nodes. Then, for each node in the table, I sent findNodeReq with ids generated after a formula containing my static id and nodes ids, to get other nodes and so on. (The static ID is the same just for an instance of the app)

Then I catch infohashes on get_peers and announce_peer messages

**Comment by Raxvis** [comment]
How does the info from announce_peer requests get to your nodes?  If you are behind a phone hotspot, are you creating UPnP tunnels back to your node?

**Comment by simionrobert** [comment]
No, I am not creating tunnels. 
Indeed, the majority of infohashes I catch is on get_peers messages. I remember one or two cases on announce_peer msg in a 10 min crawling. (In 2 minutes I get arround 300-400 infohashes with the phone network speed).

However, the speed of crawling is quite slow. 
My assumption is that this happens because the majority of nodes have implemented themselves a protection mechanism for the sybil attack.

**Comment by Raxvis** [comment]
That would make sense since a sybil attack would cripple the DHT network.

Crawling with the current setup right now on a dedicated node (not behind anything) gathers half a million torrents in 3-4 days.  I am working on upgrading the current code to try and make neighbors so announce_peer will work better

**Comment by simionrobert** [comment]
I have one more question: Will it work if I connect directly to the ISP cable? They guarantee a public IP, but I don't know if their routers are interfering with messages from the other nodes.

**Comment by Raxvis** [comment]
You will need to ensure that all traffic is pointed to your node through your router.  It might work then.  You will need to setup a DMZ for your computer, or forward traffic for all ports to your node.

**Comment by simionrobert** [comment]
Only that I can't to these because The ISP doesn't allow me to.
I was wondering if the direct connection with the ISP's cable is sufficient.

**Comment by Raxvis** [comment]
I am not sure.  I don't know if your PC will be able to handle the ISP connection without the router.

**Comment by simionrobert** [comment]
It's Russia PPOE authentification and it handles it.
What router are you talking about? Maybe I misunderstood you

**Comment by Raxvis** [comment]
The router that terminates the ISP cable?

**Comment by simionrobert** [comment]
That router belongs to me. It's a wireless router, but I also can connect directly the ISP cable (Ethernet) to the computer. I was refering to the routers outside my reach, the ISP routers. Maybe you too?

**Comment by Raxvis** [comment]
I was talking about the local router that you own.  I assumed it was provided by the ISP.  If you can connect directly to the ISP cable, then you might be able to run this directly from your computer.

**Comment by simionrobert** [comment]
Ok. Thank for your support.

**Comment by Raxvis** [comment]
NP
