### ISSUE TITLE
Creation times

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#25]
Hello im using the old version before you made some big changes. But for some reason all the torrents being added say they were uploaded 2 hours ago for every torrent. Any suggestions ?

**Comment by Raxvis** [comment]
Take a look at the script that is updated the date created time. That might
be working incorrectly.

**Comment by ghost** [comment]
Seems to vary accross different vps providers. Digital oceon works. Then other vps sometimes it has same wrong creation time and sometimes no creation time :/ i follow the same procedure accross other vps using yum install .... any suggestions mate ?

**Comment by Raxvis** [comment]
Does it only work on the main node for elasticsearch?
