### ISSUE TITLE
DHT Crawling Issue

### ISSUE THREAD

**Issue by simionrobert** [AlphaReign/scraper#26]
Hi again

What's the logical explanation behind dht crawling? You just send find_node requests and wait for get_peers and announce_infohashes?
How does other nodes save your id in their routing table?

Thanks.

**Comment by Raxvis** [comment]
An id is created on startup to ensure it’s the same id used on the dht network everywhere.

find_nodes is only called when idle so that the application doesn’t get overwhelmed with requests.

**Comment by simionrobert** [comment]
How do you ensure you get get_peers/announce_peer  request?

**Comment by Raxvis** [comment]
Use a node that lives on the internet with a fixed IP.  Having the ability for the node to be queried without a UDP tunnel or a UPnP passthrough. 

Also ensure that you return valid responses all the time and don’t flood the network so fast you get blacklisted.

**Comment by simionrobert** [comment]
I am not sure you understood what I was asking :)

What i am refering to is how do you manage to crawl infohashes form the dht network just by sending find_node request to random targets?

**Comment by simionrobert** [comment]
What crawling mechanism have you implemented? Do you passively observe infohashes or some kind of Sybil Attack? What's the meaning behind the algorithm? 
Thanks

**Comment by Raxvis** [comment]
Oh. Gotcha. Okay. So once you have a dht client up and running and you send off a bunch of find_node requests, a bunch of other clients have you IP and port in their dht table. Then when one of these other clients get peer request for looking up torrent information, they will send a request to each node for information on that torrent. That means that all I have to do is wait for a request to be made to my node to get the infohash they are looking for. Then I take that information and send out the request along to the nodes in my dht table to get the torrent information.

**Comment by Raxvis** [comment]
It’s a passive crawler for infohash information and an active crawler for dht node information

**Comment by simionrobert** [comment]
Okay. What I do not understand is the first part. 

I know that other nodes  have some buckets that are updated when some nodes are inactive by sending find_node with IDs close to the bucket ID. However they are not updated if those nodes are active.

So, how does other clients keep your ID and contact info in their dht table, simply by sending them find_node requests?

**Comment by Raxvis** [comment]
Pretty much. This code is constantly sending out find_node requests so it should be actively keeping itself alive for clients that are pruning inactive nodes. 

I also believe that many clients keep a hash table of all clients they have connected to that they can try and query and if that query fails, only then will they remove that node from their list.

**Comment by simionrobert** [comment]
Indeed, that is true. But, before trying to be kept alive, how do we, firsthand, insert ourselves in their routing table using just find_node request?

**Comment by Raxvis** [comment]
Using bootstrap nodes, we get a list of active nodes they have and then query them with find_nodes.  That’s gives us our first initial list of active clients that we can start querying.

**Comment by simionrobert** [comment]
Assume we are a node. 
I searched everywhere and I have found that updating a node routing table is by issuing find_node request to construct k-buckets.
It doesn't say anything about updating the routing table by find_node requests sent to them. 

This is what I am refering to. How do we ensure other nodes insert our ID in their routing table?

**Comment by simionrobert** [comment]
Am I a bit more clear on this?

**Comment by Raxvis** [comment]
I believe I understand what you are saying but I don’t know if what you are saying is in fact completely true. 

I am describing how this crawler works. And it does work. I have half a million torrents indexed on a little test server that I use to test modifications to the code on. 

While I don’t know exactly how other clients are keeping their tables up to date, I do know that after announcing my node through find_nodes, that I will soon start to receive queries from other nodes.

**Comment by simionrobert** [comment]
Okay. Heuristical approach :)) 

A few more questions: When was the last time you indexed those torrents? Have you tested it recently? What's the rate of indexing now? 

You are doing a good job.
Thank you.

**Comment by ghost** [comment]
Take a look at https://skytorrents.lol this is an active torrent site using thw scraper

**Comment by Raxvis** [comment]
Those torrents where indexed a couple of weeks ago. Right before I pushed the last big round of changes.

I don’t know the current rate as I am out of town this week. I plan to follow up shortly when I get back as I need to add elasticsearch and redid back as datastores.

Before, I was getting a few hundred a minute. The issue with this is that the local dht network around the node will only contain a subset of torrent information. This is actually the problem I am going to be tackling next for alpha reign is to allow alpha reign nodes to share their torrent indexes.

**Comment by Raxvis** [comment]
@ash121121 is sky torrents your site?

**Comment by simionrobert** [comment]
Ah, one more thing. 
Are you getting infohashes **mostly** through announce_peer() or through get_peers() requests?

**Comment by ghost** [comment]
Yes it is

**Comment by Raxvis** [comment]
@simionrobert I believe mostly through announce_peer
