### ISSUE TITLE
Port Scan

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#27]
Wondering if you can help. im using a server at hetzner and tried using the scraper ( the old one before you updated ) and 5 mins later i got this email below.. now what do you reccomend? kind regards.

We have indications that there was an attack from your server.
Please take all necessary measures to avoid this in the future and to solve the issue.

We also request that you send a short response to us. This response should contain information about how this could have happened and what you intend to do about it.
In the event that the following steps are not completed successfully, your server can be blocked at any time after the 2018-06-25 14:27:04 +0200.

 ##########################################################################
> #              Portscan detected from host  xxxx               #
> ##########################################################################
> 
> time                protocol src_ip src_port          dest_ip dest_port
> ---------------------------------------------------------------------------
> Sun Jun 24 00:24:35 2018 UDP   xxxx 6881  =>      172.17.0.1 59336
> Sun Jun 24 00:24:17 2018 UDP   xxxxxx 6881  =>   100.83.28.179 60693
> Sun Jun 24 00:26:15 2018 UDP  xxxxx 6881  =>   100.83.28.179 60693
> Sun Jun 24 00:22:54 2018 UDP   xxxxxx 6881  =>     10.123.89.1 49453

**Comment by WarezAddict-com** [comment]
I recommend changing hosting providers... sometimes things can be somewhat "over secure", for a lack of better terms, and cause problems and headaches.

I'm guessing you can not disable this from your hosting control panel or whatever you use??? I would say the network nerds that work for this company monitor their entire network/data center and they detected it... which means it's nothing you can disable or do.

Before the support tickets get flying and emails get exchanging, it's probably not a good idea to raise much hell about it. I've personally been booted from 2 different hosting providers in the past for pretty much the same thing. Hosting companies don't even want the risk of hosting something like Alpha Reign (or any DHT torrent/movie/pirated content site).

My best advice to you... play dumb, format/wipe/reinstall everything on that server, play dumb and don't admit to anything, and find a different hosting provider. I've been terminated for violation of ToS, literally a few days after paying for a year in advance. Guess who didn't get a refund and threatened with legal actions when demanding my money back?

Yep, this guy... right here. Its really not worth the trouble and bs!

**Comment by Raxvis** [comment]
WarezAddict is probably right.

The thing is, is that AlphaReign pushes a lot of data, and that coming from one server on tons of different ports looks like an attack.  For the hosting provider, it's easier to just shut down the one server than look into it and investigate it.

**Comment by WarezAddict-com** [comment]
BTW, I forgot to mention this....

The logs and IPs you see in that email are completely normal... since somebody, not you (remember? PLAY DUMB!), was running some kind of DHT scraper hack virus thung that listens on UDP port 6881 and communicates with tons (no, fuck loads) of devices all around the world. Depending on the settings in your config, it also uses massive amounts of bandwidth and makes any monitor/admin go crazy!

**Comment by ghost** [comment]
I manged to fix this by dropping packets to reserved ips in iptables. Thanks for your support

**Comment by Raxvis** [comment]
Awesome!
