### ISSUE TITLE
filters

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#38]
ive been messing around with the filters and can see that stuff inside the filters still end up in elasticsearch.
it looks like for some reason its not checking if the word appears in a string but only if its a full match.

**Comment by ghost** [comment]
@Prefinem  @ #39

**Comment by ghost** [comment]
looks like my fix doesnt fix it. can you take a look please @Prefinem

**Comment by Raxvis** [comment]
I will take a look tomorrow since I am out of pocket all weekend

**Comment by ghost** [comment]
Thanks mate
