### ISSUE TITLE
0 size

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#40]
Hello. it seems that we are getting that bug that you had in the previous scraper were some torrents are entering with no file size.

I remember fixing this in the last version but can't remember how lol.

**Comment by ghost** [comment]
It looks like if there is only one file in the torrent . Example if the torrent is called example.avi and that is the only file . then the files are being recorded as "[]" when it should be `[{"length":846813076,"path":["example.avi"]}]
`
@Prefinem

**Comment by Raxvis** [comment]
Should be fixed now
