### ISSUE TITLE
blank tags & type

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#43]
It seems since the new updates, that all torrents entering now have no type or tags. @Prefinem can you help please

**Comment by milezzz** [comment]
Can confirm @Prefinem. Tags column is blank for me in the database for all.

**Comment by ghost** [comment]
Maybe it's my update for the filter torrents function causing this issue. I'll roll back the code and test

**Comment by Raxvis** [comment]
Okay.  I will look at it tonight.  @ash121121 let me know if reverting your changes fixes the issue

**Comment by Raxvis** [comment]
@ash121121 Can you test this branch: https://github.com/AlphaReign/scraper/tree/split-fix ?  There are a lot of changes to split things up which will allow me to add tests around each function to start ensuring we test everything and keep from breaking things with changes

**Comment by ghost** [comment]
Sure I'll be on in around an hour to test

**Comment by ash121121** [comment]
Can I just pull this and run yarn migrate? Or start fresh

**Comment by ghost** [comment]
@Prefinem  i get this trying to run

 pm2 start ecosystem.config.js
[PM2][WARN] Applications crawler, tracker, logger, indexer not running, starting...
[PM2][ERROR] script not found : /root/scraper/src/crawler.js
[PM2][ERROR] script not found : /root/scraper/src/tracker.js
[PM2][ERROR] script not found : /root/scraper/src/logger.js
[PM2][ERROR] script not found : /root/scraper/src/indexer.js

**Comment by Raxvis** [comment]
I will fix it when I get back from lunch. They need to point to the index
file in the folder.

**Comment by ghost** [comment]
@Prefinem ok, I updated ecosystem to point to the index files. Doesn't seem to be getting any torrents

```
logger > Total Torrents: 0                                                                                        x
x                                                xx logger > Torrents without Tracker: 0                                                                              x
x                                                xx logger > Torrents not in Search: 0                                                                                x
x                                                xx PM2 > App [tracker:1] exited with code [0] via signal [SIGINT]                                                    x
x                                                xx PM2 > App [tracker:1] starting in -fork mode-                                                                     x
x                                                xx PM2 > App [tracker:1] online                                                                                      x
x                                                xx PM2 > App [tracker:1] exited with code [0] via signal [SIGINT]                                                    x
x                                                xx PM2 > App [tracker:1] starting in -fork mode-                                                                     x
x                                                xx PM2 > App [tracker:1] online   
```

**Comment by ghost** [comment]
i also reverted the changes I made back to your original code and see the same result as above

**Comment by ghost** [comment]
I reverted my changes on the master branch and seems the tags are working again but the filters.js isnt filtering stuff out.

not sure why the split-fix branch wont work for me.

**Comment by Raxvis** [comment]
I will take a look later. In a meeting now

**Comment by ghost** [comment]
I think I fixed it. looks like i did a typo instead of 

`buildRecord(invalid, knex, { files: filesWithOriginal, infohash, name });`

should be 
`buildRecord(names, knex, { files: filesWithOriginal, infohash, name });`
@Prefinem

**Comment by ghost** [comment]
@Prefinem looks to be resolved now. Sorry for the error on my part :/

**Comment by Raxvis** [comment]
Is that on the split-fix branch?

**Comment by ghost** [comment]
no on the master. i couldnt get the split-fix branch to find any torrents.

**Comment by Raxvis** [comment]
Okay thanks.  Can you make a pull request for that branch? I will try and incorporate it into the split-fix branch since that will be easier to maintain in the long wrong

**Comment by milezzz** [comment]
Tags/types confirmed working on my instance. Awesome job @ash121121

**Comment by ghost** [comment]
@Prefinem I added a pull request to fix tags issue and deny torrents with 0 size.  Not sure if I did the pull correctly, I'm new to this.

P.S .. i also did a pull request on www-php to fix my previous pull request. i forgot to put the fix in the foreach loop.
