### ISSUE TITLE
Dates

### ISSUE THREAD

**Issue by ghost** [AlphaReign/scraper#54]
Hello. There seems to be a bug. On some torrents, the trackerUpdated date is before the creation date. see below.

```
Created = 2019-02-09 17:10:16 
Updated =  2019-02-09 17:10:16
TrackerUpdated = 2019-02-09 16:10:2
```
Acccording to this the tracker was updated 1 hour before the torrent was created.

kind regards @Prefinem

**Comment by ghost** [comment]
Looks like it is because im running 2 trackers. Although they are both in the same region. they are an hour apart. Would it be wise we set a date with a timezone as default? would also save issues when migrating to a new server with a different timezone, that would mess stuff up? @Prefinem 

Or we put in the readme to make sure all servers have same timezone...

**Comment by Raxvis** [comment]
Probably.  I guess I always assumed UTC time was being sent across and not local time

**Comment by ghost** [comment]
It seems it's being sent by what the system time zone is. I had 2 servers and one was set to UTC and one to Europe/Berlin
That's what caused the issue :)
Simply changing the time zone to match the other server solved this.

**Comment by Raxvis** [comment]
Awesome.  Thanks for updating me

**Comment by ghost** [comment]
No problem
