### ISSUE TITLE
Help understanding scraper

### ISSUE THREAD

**Issue by konsumer** [AlphaReign/scraper#7]
I'd like to make my own index of torrents.  How does this work? It appears that it needs to already know about the torrents to get the file info from them? Where do you get your list of torrents?

**Comment by Raxvis** [comment]
The scraper itself gathers the torrents from the DHT network so you don't have to get a list of torrents.

**Comment by konsumer** [comment]
Oh, rad! So I just start up the daemon and it collects info automatically?

**Comment by Raxvis** [comment]
Yes, but you will need to make sure you have port forwarding on so that DHT requests can hit the scraper

**Comment by konsumer** [comment]
I'm not sure I understand. I need to route torrent traffic through the daemon?

**Comment by Raxvis** [comment]
The indexer (daemon) needs to be exposed to the outside world in terms of the public internet.  That means that whatever port the indexer is listening on (usually 6881) needs to be accessible from an IP by anyone

**Comment by sayak-brm** [comment]
So elastic search is to be installed using npm?

And how to setup configure.json?

**Comment by sayak-brm** [comment]
"Yes, but you will need to make sure you have port forwarding on so that DHT requests can hit the scraper"

Which ports?

**Comment by Raxvis** [comment]
ElasticSearch is not installed by npm

**Comment by konsumer** [comment]
@Prefinem ah! thanks.

**Comment by Raxvis** [comment]
NP
