### ISSUE TITLE
Old data available?

### ISSUE THREAD

**Issue by schmiedecker** [AlphaReign/scraper#8]
Would be great if the collected data could be shared - I'd be willing to host it, probably too big for github.

**Comment by Raxvis** [comment]
Here is a redis dump file of 3 million torrents

https://mega.nz/#!sagEyY6S!gTEqZv9BqjPWQVZyjFwYOD5GtmU6_3OkF1nl01z2NE8

**Comment by ghost** [comment]
Is it possible to use this database in elasticsearch?
